version: '3.5'

services:
  grontopi:
    container_name: grontopi
    depends_on:
      - redis_cache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
      - ./grontopi:/app
    ports:
      - 8000:80
    environment:
      - LOG_LEVEL=debug
      - MAX_WORKERS=1
      - CONFIG_PATH=/config/angelus_config.json
    entrypoint: /start-reload.sh

  redis_cache:
    image: redis:5.0.5
    container_name: redis_cache

  fuseki:
    container_name: local_fuseki
    image: atomgraph/fuseki
    command: "--file=/usr/share/data/tripletas_angelus_publico.n3 /ds"
    volumes:
      - ./sample_data:/usr/share/data
    ports:
      - 3030:3030
